### ISSUE TITLE
versions!

### ISSUE THREAD

**Issue by ChouChou1879** [emmanuelballery/orange-billing-enabler#3]
Hello
pour la BDD, c'est quelle version ?
et PHP?
et tout le reste !
c'est pour faire le pipeline de déploiement.
merci !!!

**Comment by emmanuelballery** [comment]
Je t'ai pris exactement la même config que le bridge océane pour que tu puisses reprendre le même build

**Comment by ChouChou1879** [comment]
super merci <3

**Comment by ChouChou1879** [comment]
y'a zéro secret à part le pwd de la BDD en gros c'est ça?
dans.env je ne vois pas grand chose.
L'api n'est pas protégée pour l'instant?

**Comment by emmanuelballery** [comment]
l'API c'est test/test en basic tant que je ne sais pas comment on doit se loguer.

Il y a le mot de passe redis aussi mais c'est pas vraiment un secret.
