### ISSUE TITLE
pipeline - questions

### ISSUE THREAD

**Issue by ChouChou1879** [emmanuelballery/orange-billing-enabler#4]
hello
bon j'ai essayé de faire le pipeline tant bien que mal...
ça coince évidemment...

je te mets les logs..
y'a des trucs node.. surement pour des trucs de tests... 
il cherche un fichier de test.. je ne sais ou... aprèps j'ai copié des trucs du bridge pour le déploiement...
mais là je ne vois pas trop! si tu as une idée!
je t'ai mis les logs en dessous !

Running with gitlab-runner 14.10.0 (c6bb62f6)
  on gr-gitlab-tech-orange-gitlab-runner-7c8c85648f-869rq DWGx_FUK
Preparing the "kubernetes" executor 00:00
Using Kubernetes namespace: gitlab-tech-orange
Using Kubernetes executor with image node:lts-alpine ...
Using attach strategy to execute scripts...
Preparing environment 00:10
Waiting for pod gitlab-tech-orange/runner-dwgxfuk-project-208991-concurrent-07tprj to be running, status is Pending
Running on runner-dwgxfuk-project-208991-concurrent-07tprj via gr-gitlab-tech-orange-gitlab-runner-7c8c85648f-869rq...
Getting source from Git repository 00:01
$ job_announcement() { # JOB ANNOUNCEMENT # collapsed multi-line command
 
 INFO You are using GRaaS runners (https://devops-store.rd.francetelecom.fr/en/edition/topic/show/graas) 
 You can find the documentation here https://graas.pages.gitlab.tech.orange/shared-runner/doc/ 
 WARNING You are responsible for what you are doing in your jobs! 
 We can not be responsible if you jeopardize the security of Orange. 
 We also reserve the right to ban any project that would jeopardize the security of Orange.
 
 IMPORTANT Please note the dates of the following services EOL 
 	Artifactory (https://devops-store.rd.francetelecom.fr/en/edition/topic/show/artifactory) 
 		 artifactory-iva.si.francetelecom.fr will be stopped the 30/09/2022 
 		 artifactory.tech.orange will be stopped the 30/12/2022 
 	Nexus (ex R&D) (https://maven2.rd.francetelecom.fr/) will be stopped the 31/10/2022 
 	Repo YUM (https://devops-store.rd.francetelecom.fr/en/edition/topic/show/repo-yum) and APT-Cacher (https://devops-store.rd.francetelecom.fr/en/edition/topic/show/apt-cacher) will be stopped soon too
 All these services are replaced by the DIOD Central Repository solution (https://devops-store.rd.francetelecom.fr/en/edition/topic/show/diod-central-repository) 
 For further details see https://plazza.orange.com/docs/DOC-2176218
 
Fetching changes with git depth set to 20...
Initialized empty Git repository in /builds/ubicode/diod-console/billing-aggregator/.git/
Created fresh repository.
Checking out d83ac40c as main...
Skipping Git submodules setup
Restoring cache 00:00
Checking cache for main-node-protected...
WARNING: file does not exist                       
Failed to extract cache
Executing "step_script" stage of the job script 00:10
$ ( # collapsed multi-line command
$ # BEGSCRIPT # collapsed multi-line command
wget: server returned error: HTTP/1.1 404 Not Found
$ install_ca_certs "${CUSTOM_CA_CERTS:-$DEFAULT_CA_CERTS}"
[INFO] CA certificates imported in /etc/ssl/certs/ca-certificates.crt
[INFO] CA certificates imported in /etc/ssl/cert.pem
$ cd ${NODE_PROJECT_DIR}
$ if [[ "$NPM_CONFIG_REGISTRY" ]]; then npm config set registry $NPM_CONFIG_REGISTRY; fi
$ npm ci --cache .npm --prefer-offline
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
added 723 packages, and audited 724 packages in 9s
78 packages are looking for funding
  run `npm fund` for details
1 high severity vulnerability
To address all issues, run:
  npm audit fix
Run `npm audit` for details.
$ npm $NODE_TEST_ARGS
npm ERR! Missing script: "test"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-23T08_22_22_307Z-debug-0.log
Uploading artifacts for failed job 00:00
Uploading artifacts...
WARNING: ./public/build: no matching files         
WARNING: ./reports/: no matching files             
ERROR: No files to upload                          
Uploading artifacts...
WARNING: ./reports/unit_test_report.xml: no matching files 
ERROR: No files to upload                          
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: command terminated with exit code 1

**Comment by emmanuelballery** [comment]
Tout se passe bien jusqu'à `npm $NODE_TEST_ARGS` et ça dit `npm ERR! Missing script: "test"` donc j'imagine qu'il lance un truc comme `npm run test` mais ce n'est pas une commande valide.

Je ne peux pas voir ce projet sur Gitlab, tu peux m'autoriser pour que j'ai plus de détails ?

**Comment by ChouChou1879** [comment]
je t'ai invité! mais du coup ça passe par le mail orange.
https://gitlab.tech.orange/ubicode/diod-console/billing-aggregator/

Je n'arrive pas à voir ou est lancée cette commande... :( suis pas douée...

**Comment by lyandr** [comment]
Hello @ChouChou1879, cela vient du template ci-cd node qui impose des bonnes pratiques tel que le lancement de tests, mais le dev à qui tu fais appelles n'en fait pas xD

La solution que je mets en place est de mettre ça dans le package.json dans la section scripts:
```json
"scripts": {
        ...
        "test": "echo 'test'"
    },

```

**Comment by emmanuelballery** [comment]
On est fort en bonne pratique nous !

**Comment by emmanuelballery** [comment]
Merci @lyandr

**Comment by ChouChou1879** [comment]
c'est passé!
maintenant celà bloque ici:
etching changes with git depth set to 20...
Initialized empty Git repository in /builds/ubicode/diod-console/billing-aggregator/.git/
Created fresh repository.
Checking out f14c55e3 as main...
Skipping Git submodules setup
Restoring cache 00:01
Checking cache for main-node-protected...
Downloading cache.zip from https://oss.eu-west-0.prod-cloud-ocb.orange-business.com/graas-cache/gitlab-tech-orange/project/208991/main-node-protected 
Successfully extracted cache
Downloading artifacts 00:01
Downloading artifacts for docker-hadolint (43038625)...
Downloading artifacts from coordinator... ok        id=43038625 responseStatus=200 OK token=LbpUf3tD
Downloading artifacts for node-build (43038626)...
Downloading artifacts from coordinator... ok        id=43038626 responseStatus=200 OK token=_udPfbmp
Executing "step_script" stage of the job script 00:13
$ ( # collapsed multi-line command
$ # BEGSCRIPT # collapsed multi-line command
wget: server returned error: HTTP/1.1 404 Not Found
$ install_ca_certs "${CUSTOM_CA_CERTS:-$DEFAULT_CA_CERTS}"
[INFO] CA certificates imported in /etc/ssl/certs/ca-certificates.crt
[INFO] CA certificates imported in /etc/ssl/cert.pem
$ cd ${NODE_PROJECT_DIR}
$ if [[ "$NPM_CONFIG_REGISTRY" ]]; then npm config set registry $NPM_CONFIG_REGISTRY; fi
$ npm ci --cache .npm --prefer-offline
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
added 723 packages, and audited 724 packages in 5s
78 packages are looking for funding
  run `npm fund` for details
1 high severity vulnerability
To address all issues, run:
  npm audit fix
Run `npm audit` for details.
$ mkdir -p reports
$ npm audit --json $NODE_AUDIT_ARGS | tee $NODE_AUDIT_JSON_PATH | npx npm-audit-html $NODE_AUDIT_HTML_ARGS
npm WARN exec The following package was not found and will be installed: npm-audit-html@1.5.0
Vulnerability snapshot saved at reports/npm-audit-report.html
Uploading artifacts for failed job 00:01
Uploading artifacts...
./reports/: found 5 matching files and directories 
Uploading artifacts as "archive" to coordinator... 201 Created  id=43038627 responseStatus=201 Created token=bebWhdE5
Cleaning up project directory and file based variables

**Comment by emmanuelballery** [comment]
Regarde : https://github.com/emmanuelballery/orange-billing-enabler/blob/master/subscription.http

Il fallait voir si le schema était acceptable et on doit faire un point pour la suite (auth, droits, ...).
