### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ChouChou1879** [emmanuelballery/orange-billing-enabler#5]
hello
j'ai fait ma première requête!
une commande à passer peut être?
10.129.2.1 - - [25/Aug/2022:08:49:21 +0000] "GET /aapi//subscriptions HTTP/1.1" 404 538 "-" "PostmanRuntime/7.29.2"
{"message":"Matched route \"api_subscriptions_get_collection\".","context":{"route":"api_subscriptions_get_collection","route_parameters":{"_route":"api_subscriptions_get_collection","_controller":"api_platform.action.get_collection","_format":null,"_stateless":null,"_api_resource_class":"App\\Entity\\Subscription","_api_identifiers":["id"],"_api_has_composite_identifier":false,"_api_collection_operation_name":"get"},"request_uri":"https://billing-aggregator-staging.apps.fr01.paas.tech.orange/api/subscriptions","method":"GET"},"level":200,"level_name":"INFO","channel":"request","datetime":"2022-08-25T10:49:47.065525+02:00","extra":{}}
{"message":"Uncaught PHP Exception Doctrine\\DBAL\\Exception\\TableNotFoundException: \"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aggregator.billing_subscription' doesn't exist\" at /var/www/localhost/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 51","context":{"exception":{"class":"Doctrine\\DBAL\\Exception\\TableNotFoundException","message":"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aggregator.billing_subscription' doesn't exist","code":1146,"file":"/var/www/localhost/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:51","previous":{"class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aggregator.billing_subscription' doesn't exist","code":1146,"file":"/var/www/localhost/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30","previous":{"class":"PDOException","message":"SQLSTATE[
42S02]: Base table or view not found: 1146 Table 'aggregator.billing_subscription' doesn't exist","code":42,"file":"/var/www/localhost/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72"}}}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2022-08-25T10:49:47.125925+02:00","extra":{}}
10.129.2.1 - test [25/Aug/2022:08:49:47 +0000] "GET /api/subscriptions HTTP/1.1" 500 133 "-" "PostmanRuntime/7.29.2"

**Comment by emmanuelballery** [comment]
La migration de la BDD ? C'est pas auto dans le pipeline ?

`php bin/console do:mi:mi -n -e prod`

**Comment by ChouChou1879** [comment]
rhaaa tu appuies ou ça fait mal! sadique!
j'en sais rien pour tt te dire...
Ce que je sais c'est que pour chaque migration de schéma q ça soit diod live...Aviso etc je passe la commande à la main sur le pod !!!

**Comment by ChouChou1879** [comment]
résultat de la commande:

/var/www/localhost $ php bin/console do:mi:mi -n -e prod
[2022-08-25T12:00:39.205590+02:00] deprecation.INFO: User Deprecated: Since symfony/redis-messenger 5.4: Not setting the "delete_after_ack" boolean option explicitly is deprecated, its default value will change to true in 6.0. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/redis-messenger 5.4: Not setting the \"delete_after_ack\" boolean option explicitly is deprecated, its default value will change to true in 6.0. at /var/www/localhost/vendor/symfony/redis-messenger/Transport/Connection.php:192)"} []
[notice] Migrating up to DoctrineMigrations\Version20220713205101
[notice] finished in 40.8ms, used 6M memory, 1 migrations executed, 1 sql queries

**Comment by ChouChou1879** [comment]
c'est bon maintenant!
je tente un POST!

**Comment by ChouChou1879** [comment]
test:
J'ai essayé en remplissant tous les "cost" .. mais ça ne veut pas!
je te mets les logs dessous !
{
    "subscriptionId": "lnp1ppz8a-OPENSHIFT-31220955",
    "key": "Customer account",
    "value": "testChristine",
    "cost": null,
    "start": "2022-08-01T00:00:00.000Z",
    "end": null,
    "periodicity": "monthly",
    "rows": [
        {
            "key": "Namespace",
            "value": "application1",
            "cost": 6.15,
            "rows": [
                {
                    "key": "CPU",
                    "value": "0,005",
                    "unit": "CPU",
                    "cost": null
                },
                {
                    "key": "Memmory",
                    "value": "0.088",
                    "unit": "Go",
                    "cost": null
                }
            ]
        },
        {
            "key": "Namespace",
            "value": "application2",
            "cost": 10.20,
            "rows": [
                {
                    "key": "CPU",
                    "value": "0,007",
                    "unit": "CPU",
                    "cost": null
                },
                {
                    "key": "Memmory",
                    "value": "0.125",
                    "unit": "Go",
                    "cost": null
                }
            ]
        }  
    ]
}

Logs:
{
    "type": "https://tools.ietf.org/html/rfc2616#section-10",
    "title": "An error occurred",
    "detail": "rows[0].cost: Either fill the cost or add rows.\nrows[0].rows[0].cost: This value should not be null.\nrows[0].rows[1].cost: This value should not be null.\nrows[1].cost: Either fill the cost or add rows.\nrows[1].rows[0].cost: This value should not be null.\nrows[1].rows[1].cost: This value should not be null.",
    "violations": [
        {
            "propertyPath": "rows[0].cost",
            "message": "Either fill the cost or add rows.",
            "code": "@todo"
        },
        {
            "propertyPath": "rows[0].rows[0].cost",
            "message": "This value should not be null.",
            "code": "ad32d13f-c3d4-423b-909a-857b961eb720"
        },
        {
            "propertyPath": "rows[0].rows[1].cost",
            "message": "This value should not be null.",
            "code": "ad32d13f-c3d4-423b-909a-857b961eb720"
        },
        {
            "propertyPath": "rows[1].cost",
            "message": "Either fill the cost or add rows.",
            "code": "@todo"
        },
        {
            "propertyPath": "rows[1].rows[0].cost",
            "message": "This value should not be null.",
            "code": "ad32d13f-c3d4-423b-909a-857b961eb720"
        },
        {
            "propertyPath": "rows[1].rows[1].cost",
            "message": "This value should not be null.",
            "code": "ad32d13f-c3d4-423b-909a-857b961eb720"
        }
    ]
}

**Comment by emmanuelballery** [comment]
On est bon. C'est juste que dans ma tête si tu mets `null` dans un `cost` c'est que tu décris dans les enfants (`rows`) les `cost` des enfants (et que la somme donne le `cost` du parent). Mais après coup j'avais compris que ça ne marchait pas vraiment comme ça.

**Comment by ChouChou1879** [comment]
oui c'est ça, ça remonte!
mais dès fois ils n'ont pas le détails du prix des rows. et on a que le cost.
J'ai refait un essai ==> j'ai mis que les cost des row. c'est passé.
Par contre en faisant le GET, cela ne calcule pas encore, c'est ça?

**Comment by emmanuelballery** [comment]
Non, pas de recalcule parceque je doutais de ma méthode. Et elle est mauvaise.

Du coup on a plus qu'à faire un point de situ pour avancer si on est bon côté déploiement.

**Comment by ChouChou1879** [comment]
oui le déploiement est ok !!
