### ISSUE TITLE
Nouvelle version

### ISSUE THREAD

**Issue by emmanuelballery** [emmanuelballery/orange-billing-enabler#6]
Hello @ChouChou1879,

Ça va faire beaucoup d'un coup mais on va y arriver.

## Bridges

J'ai ajouté 4 bridges vers d'autres API :

- **clarity** (pour accéder aux projets clarity)
- **offer** (pour accéder aux offres)
- **project** (nouvelle api des projets)
- **token** (pour gérer les tokens ODI)

4 caches Redis : 1 pour chaque bridge ;

4 channels indépendants de logs pour chaque bridge pour que l'on retrace mieux ce qu'il se passe ;

4 commandes disponibles pour tester en console :
- `php bin/console orange:clarity:find <ID>` pour chercher un projet clarity
- `php bin/console orange:offer:find <ID>` pour chercher une offre
- `php bin/console orange:project:find <ID>` pour chercher un projet
- `php bin/console orange:token` pour générer un token ODI

## Base de données

Dans la base de données on gère désormais les **Client** de l'API

- `id` (UUID)
- `name` (string)
- `owner` (CUID du référent pour savoir à qui s'adresser)
- `clientId` (client id généré par l'application)
- `clientSecret` (client secret généré par l'application)
- `offerIds` (tableau d'ids d'offres eg `["DATAPROCESSING"]`)
- `isEnabled` (bool)

## API

Il existe une API pour gérer les **Client**, elle est réservée à un ADMIN (il se connecte en basic avec les identifiants rangés dans les vars d'env `ADMIN_CLIENT_ID` et `ADMIN_CLIENT_SECRET`) ; un client ne se supprime pas car les `Subscription` qu'il ajoute lui sont associés à vie, mais on peut le désactiver ;

L'API des `Subscription` est accessible aux clients ; ils ne peuvent créer que sur les `offerId` de leur périmètre et ne peuvent lire que dans ce périmètre aussi.

## Enrichissement de Subscription

En créant une Subscription, on réalise les opérations suivantes :

- décomposition de `subscriptionId` en `diodId`, `offerId` et `randomId` ;
- recherche d'un projet sur le ref **project** via le `diodId`
- on renseigne le `projectId` via le `projet` trouvé
- recherche d'une offre sur le ref **offer** via le `offerId`
- décomposition du `billingCode` de `project` (aucune idée si c'est ce qu'il faut faire) pour obtenir la dernière partie qui est le `clarityId`
- recherche d'un projet clarity sur le ref **clarity** via le `clarityId`
- si un des `cost` est `null`, on tente de le remplir en calculant via la somme des `cost` de ses enfants (si un `cost` enfant est `null` c'est l'échec)
- le `cost` à la racine est obligatoire après cette manipulation

### Retirer

```env
MESSENGER_TRANSPORT_DSN
```

### Ajouter

Je t'ai renseigné les variables telles que je les imagine à l'heure actuelle ... pas certain.

```env
# Lock Redis : https://symfony.com/doc/current/lock.html#configuring-lock-with-frameworkbundle
LOCK_DSN=redis://password@127.0.0.1:6379

# Cache Redis : https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html#configure-the-connection
CACHE_REDIS_DSN=redis://password@127.0.0.1:6379

# Http
HTTP_CLIENT_TIMEOUT=2
HTTP_CLIENT_MAX_DURATION=2

# Admin
ADMIN_CLIENT_ID=<identifiant qu'utilisera ton admin>
ADMIN_CLIENT_SECRET=<mot de passe qu'utilisera ton admin>

# Token ODI: usage "{TOKEN_BASE_URI}/v3/token"
TOKEN_BASE_URI=https://inside01.api.intraorange/oauth
TOKEN_CLIENT_ID=<le client id pour obtenir des tokens>
TOKEN_CLIENT_SECRET=<le client secret pour obtenir des tokens>

# Clarity: usage "{CLARITY_BASE_URI}/v1/projects"
CLARITY_CACHE_LIFETIME=864000 <------- les appels sont mis en cache 10 jours
CLARITY_BASE_URI=https://inside01.api.intraorange/diod/is/clarity-management

# Offer: usage "{OFFER_BASE_URI}/offer/{id}"
OFFER_CACHE_LIFETIME=864000 <------- les appels sont mis en cache 10 jours
OFFER_BASE_URI=https://console-diod-staging.apps.fr01.paas.tech.orange/api
OFFER_CLIENT_ID=<le client id pour accéder aux offres>
OFFER_CLIENT_SECRET=<le client secret pour accéder aux offres>

# Project: usage "{PROJECT_BASE_URI}/v1/projects"
PROJECT_CACHE_LIFETIME=864000 <------- les appels sont mis en cache 10 jours
PROJECT_BASE_URI=https://inside01.api.intraorange/devops-store/project-management
```

**Comment by ChouChou1879** [comment]
Hello
Grâce à Yann on a pu déployer.. j'ai dû m'endormir sur la barre d'espace... ds un fichier.. Yann a corrigé..c'est ça d'être amateur et de vouloir jouer dans la courre des grands! bref!
je fais un simple GET sur les souscriptions et j'ai ça :

2022-09-05 08:46:01,389 INFO success: php8-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[05-Sep-2022 11:17:05 Europe/Paris] PHP Fatal error:  Constant expression contains invalid operations in /var/www/localhost/src/Entity/Client.php on line 85
127.0.0.1 -  05/Sep/2022:09:17:04 +0000 "GET /index.php" 500

**Comment by emmanuelballery** [comment]
Mince ça ressemble à une erreur de version PHP. Je suis en 8.1 mais vous êtes en 8.0 et j'ai sûrement raté un truc. Je vais regarder quand j'ai 2 minutes.

**Comment by ChouChou1879** [comment]
haaaaaaaaaaa
ok! dis moi et je teste ds la foulée.
Je peux aussi mettre ds le déploiement du 8.1...je regarde

**Comment by ChouChou1879** [comment]
dans composer.lock
  "require": {
                "doctrine/lexer": "1.*",
                "ext-tokenizer": "*",
                "php": "^7.1 || ^8.0",
                "psr/cache": "^1 || ^2 || ^3"
            },

**Comment by emmanuelballery** [comment]
Bein oui, je bloque PHP dans les dépendances pour éviter qu'il nous fournisse des paquets plus haut que 8.0

**Comment by ChouChou1879** [comment]
tu me diras du coup !

**Comment by ChouChou1879** [comment]
je n'ai plus d'erreur 500 mais un 401
j'ai donc mis les cred d'admin... en basic auth mais je me reprends un 500

127.0.0.1 -  05/Sep/2022:13:40:44 +0000 "GET /index.php" 401
10.130.2.1 - - [05/Sep/2022:13:40:46 +0000] "GET /api/subscriptions HTTP/1.1" 401 5 "-" "PostmanRuntime/7.29.2"
{"message":"Matched route \"api_subscriptions_get_collection\".","context":{"route":"api_subscriptions_get_collection","route_parameters":{"_route":"api_subscriptions_get_collection","_controller":"api_platform.action.get_collection","_format":null,"_stateless":null,"_api_resource_class":"App\\Entity\\Subscription","_api_identifiers":["id"],"_api_has_composite_identifier":false,"_api_collection_operation_name":"get"},"request_uri":"https://billing-aggregator-staging.apps.fr01.paas.tech.orange/api/subscriptions","method":"GET"},"level":200,"level_name":"INFO","channel":"request","datetime":"2022-09-05T15:43:16.825684+02:00","extra":{}}
{"message":"Checking for authenticator support.","context":{"firewall_name":"main","authenticators":1},"level":100,"level_name":"DEBUG","channel":"security","datetime":"2022-09-05T15:43:16.834011+02:00","extra":{}}
{"message":"Checking support on authenticator.","context":{"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"},"level":100,"level_name":"DEBUG","channel":"security","datetime":"2022-09-05T15:43:16.834025+02:00","extra":{}}
{"message":"Authenticator successful!","context":{"token":"UsernamePasswordToken(user=\"chouchou\", authenticated=true, roles=\"ROLE_ADMIN\")","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"},"level":200,"level_name":"INFO","channel":"security","datetime":"2022-09-05T15:43:16.845585+02:00","extra":{}}
{"message":"Authenticator set no success response: request continues.","context":{"authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"},"level":100,"level_name":"DEBUG","channel":"security","datetime":"2022-09-05T15:43:16.846790+02:00","extra":{}}
{"message":"Uncaught PHP Exception Doctrine\\DBAL\\Exception\\InvalidFieldNameException: \"An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'b0_.diod_id' in 'field list'\" at /var/www/localhost/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 67","context":{"exception":{"class":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException","message":"An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'b0_.diod_id' in 'field list'","code":1054,"file":"/var/www/localhost/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:67","previous":{"class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'b0_.diod_id' in 'field list'","code":1054,"file":"/var/www/localhost/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28","previous":{"class":"PDOException","message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'b0_.diod_i
d' in 'field list'","code":42,"file":"/var/www/localhost/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:69"}}}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2022-09-05T15:43:16.933735+02:00","extra":{}}
{"message":"Stored the security token in the session.","context":{"key":"_security_main"},"level":100,"level_name":"DEBUG","channel":"security","datetime":"2022-09-05T15:43:16.936097+02:00","extra":{}}
10.131.2.1 - chouchou [05/Sep/2022:13:43:16 +0000] "GET /api/subscriptions HTTP/1.1" 500 133 "-" "PostmanRuntime/7.29.2"
127.0.0.1 - chouchou 05/Sep/2022:13:43:16 +0000 "GET /index.php" 500

**Comment by emmanuelballery** [comment]
T'as migré la base ? 🤐

**Comment by ChouChou1879** [comment]
:P

**Comment by ChouChou1879** [comment]
je dois être un peu bête...
## List clients **==> OK**
GET {{host}}/api/clients
Accept: application/json
Authorization: Basic {{username}} {{password}}

### Create client **===> heuuuuuuuuuuuu tu les passes ou les login/pwd du mec qu'on autorise?**
POST {{host}}/api/clients
Content-Type: application/json
Accept: application/json
Authorization: Basic {{username}} {{password}}

< ./tests/Resources/client1.json

### Update client **===> heuuuuuuuuuuuu tu les passes ou les login/pwd du mec qu'on update?**
PUT {{host}}/api/clients/{client_id}
Content-Type: application/json
Accept: application/json
Authorization: Basic {{username}} {{password}}

< ./tests/Resources/client1.json

**Comment by ChouChou1879** [comment]
bon alors, j'ai bien créer mes cred
j'appelle pour poster une facture
j'ai eut des pb avec le ref projet donc j'ai modifié le configmap et redémarré le pod mais il me pose des pb avec les credentials.. je ne comprneds pas bien. ils sont expirés? je dois en recréer?

[06-Sep-2022 08:27:24] NOTICE: fpm is running, pid 28
[06-Sep-2022 08:27:24] NOTICE: ready to handle connections
2022-09-06 08:27:25,917 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-09-06 08:27:25,917 INFO success: php8-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2022-09-06T10:41:22.653525+02:00] deprecation.INFO: User Deprecated: Since symfony/security-http 5.3: Not implementing the "Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface" interface in class "App\Entity\Client" while using password-based authentication is deprecated. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/security-http 5.3: Not implementing the \"Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface\" interface in class \"App\\Entity\\Client\" while using password-based authentication is deprecated. at /var/www/localhost/vendor/symfony/security-http/EventListener/CheckCredentialsListener.php:58)"} []
10.128.4.1 - 6316f708d2a347.78487298 [06/Sep/2022:08:41:22 +0000] "POST /api/subscriptions HTTP/1.1" 422 246 "-" "PostmanRuntime/7.29.2"
127.0.0.1 - 6316f708d2a347.78487298 06/Sep/2022:08:41:21 +0000 "POST /index.php" 422
[2022-09-06T10:41:47.194858+02:00] deprecation.INFO: User Deprecated: Since symfony/security-http 5.3: Not implementing the "Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface" interface in class "App\Entity\Client" while using password-based authentication is deprecated. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/security-http 5.3: Not implementing the \"Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface\" interface in class \"App\\Entity\\Client\" while using password-based authentication is deprecated. at /var/www/localhost/vendor/symfony/security-http/EventListener/CheckCredentialsListener.php:58)"} []
10.129.2.1 - 6316f708d2a347.78487298 [06/Sep/2022:08:41:47 +0000] "POST /api/subscriptions HTTP/1.1" 422 246 "-" "PostmanRuntime/7.29.2"
127.0.0.1 - 6316f708d2a347.78487298 06/Sep/2022:08:41:47 +0000 "POST /index.php" 422

**Comment by emmanuelballery** [comment]
Hello ! Je vais corriger les deprecated. Par contre tu as une erreur sur la précision du cost. J'ai en effet une contrainte stipulant que le cost ne peut pas avoir plus de 2 chiffres après la virgule. Si tu envoies un cost avec plus de 2 chiffres après la virgule, alors il faut m'expliquer pourquoi. Si ce n'est pas le cas, c'est parceque PHP est un de ses langage de m***e qui pense que 1.0 + 1.0 = 2.00000000001 ... Et ça je peux l'améliorer. Par contre pas d'erreur sur project donc le référentiel doit répondre.

**Comment by emmanuelballery** [comment]
@ChouChou1879 C'est poussé !

**Comment by ChouChou1879** [comment]
c'est installé!!!
et ça MARCHE!!!!!!
chapeau! tt fonctionne ! 
je vais en faire d'autres :) je te tiens au courant !

{
    "id": "1ed2dd3b-612e-62a0-bd10-07999b94b06c",
    "client": "/api/clients/1ed2db5c-113c-6714-9fe2-01928b7c9032",
    "created": "2022-09-06T13:04:43+02:00",
    "updated": null,
    "subscriptionId": "np1ppz8a-OPENSHIFT-31220955",
    "diodId": "np1ppz8a",
    "projectId": "7b4055bc-6d26-4d3d-a89e-eada6954dc8c",
    "project": {
        "id": "7b4055bc-6d26-4d3d-a89e-eada6954dc8c",
        "name": "DIOD INTERFACES#2",
        "description": "test souscription",
        "externalId": "np1ppz8a",
        "level": "medium",
        "billingCode": "orange:billing:clarity:PJ00027084",
        "billingType": "INNOV",
        "businessTopic": "New Services",
        "beneficiaryRegion": "INNOV",
        "type": "diod",
        "status": "approved",
        "created": "2022-05-19T15:08:26+00:00",
        "updated": "2022-09-06T07:57:32+00:00",
        "endDate": "2050-01-01T00:00:00+00:00"
    },
    "offerId": "OPENSHIFT",
    "offer": {
        "id": "OPENSHIFT",
        "name": "PaaS OpenShift",
        "line": "Application Engines",
        "globalDescription": "The Platform As A Service (PaaS) OpenShift service enables developers to build their applications with the languages and tools they need. The service is based on Red Hat OpenShift version 4.x, an open source container application platform based on the Kubernetes container orchestrator for enterprise application development and deployment.",
        "description": "The PaaS OpenShift service offering consists in a Discovery offer (free), a Premium offer for standard projects and a Custom offer for larger projects. For Pay offers (Premium & Custom), customers will reserve resources they need and pay according to the reserved GB of RAM ; extra CPU/RAM can be &lt;b>reserved to fit growing usage needs as an option&lt;/b>.",
        "sla": null,
        "options": " For premium, up to 2 free CPUs are included in the offer. Extra CPU/RAM can be allocated at a fix price of 60€ / CPU / month on demand ; marketplace templates and Operators resources are included for free.",
        "calculator": "https://diod.tech.orange/wp-content/uploads/2021/04/Price-Simulator-Customer-V1.0.xlsx",
        "tags": [
            "development teams"
        ],
        "keys": [
            "Duration",
            "Ressources",
            "Pricing Terms",
            "Access"
        ],
        "plans": [
            {
                "id": "OPENSHIFT01",
                "name": "Discovery",
                "project": "discovery",
                "dosSubscriptionId": "f050c9d2-c875-4972-8aac-c1348ab4dc48",
                "active": true,
                "capabilities": [
                    "3 months",
                    "Max 2GB RAM",
                    "free",
                    "self-service"
                ]
            },
            {
                "id": "OPENSHIFT02",
                "name": "Premium",
                "project": "INNOV",
                "dosSubscriptionId": "3b8072cc-2075-4c68-a89d-0b468cf41bb3",
                "active": true,
                "capabilities": [
                    "unlimited",
                    "Max 10GB RAM",
                    "70€/month",
                    "self-service"
                ]
            },
            {
                "id": "OPENSHIFT03",
                "name": "Custom",
                "project": "INNOV",
                "dosSubscriptionId": "3b8072cc-2075-4c68-a89d-0b468cf41bb3",
                "active": true,
                "capabilities": [
                    "unlimited",
                    "> 10GB RAM",
                    "70€/RAM",
                    "self-service"
                ]
            }
        ],
        "createdAt": "2022-03-25T09:53:45+00:00",
        "updatedAt": "2022-08-30T08:32:34+00:00"
    },
    "clarityId": "PJ00027084",
    "clarity": {
        "id": "PJ00027084",
        "name": "DIOD Interface & UX",
        "status": "Approved",
        "department": "DIESE",
        "region": "SHARED",
        "portfolio": "IT-S End to End Digital & Cloud Native Environments",
        "program": "Cloud Native Secured Platform",
        "projectManager": {
            "sub": "suar7455",
            "firstName": "Soizick",
            "lastName": "Roussin",
            "email": "soizick.roussin@orange.com",
            "department": "DIESE",
            "entity": "/FT/INNOVATION/IT-S/DIESE/SAE/DEX"
        },
        "programManager": {
            "sub": "nyab7406",
            "firstName": "Nabil",
            "lastName": "Benameur",
            "email": "nabil.benameur@orange.com",
            "department": "DIESE",
            "entity": "/FT/INNOVATION/IT-S/DIESE/DIA"
        }
    },
    "randomId": "31220955",
    "key": "Customer account",
    "value": "testChristine",
    "cost": 16.38,
    "start": "2022-08-01T00:00:00+02:00",
    "end": null,
    "periodicity": "monthly",
    "rows": [
        {
            "key": "Namespace",
            "value": "application1",
            "cost": 6.15,
            "rows": [
                {
                    "key": "CPU",
                    "value": "0,005",
                    "unit": "CPU",
                    "cost": null
                },
                {
                    "key": "Memmory",
                    "value": "0.088",
                    "unit": "Go",
                    "cost": null
                }
            ]
        },
        {
            "key": "Namespace",
            "value": "application2",
            "cost": 10.23,
            "rows": [
                {
                    "key": "CPU",
                    "value": "0,007",
                    "unit": "CPU",
                    "cost": null
                },
                {
                    "key": "Memmory",
                    "value": "0.125",
                    "unit": "Go",
                    "cost": null
                }
            ]
        }
    ]
}
